version: '3'
services:
  builds-webhook:
    build: .
    command: pnpm start
    image: builds-webhook
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    container_name: builds-webhook
